import { images } from "./images";

export interface PortfolioProject {
  id: string;
  title: string;
  location: string;
  year: number;
  clients: string;
  image: string;
  category: "residential" | "commercial" | "metal" | "slate";
  roofType: string;
  sqft: number;
  homeSqft: number;
  bedrooms: number;
  bathrooms: number;
  architect: string;
  duration: string;
  elevation: string;
  tagline: string;
  overview: string;
  story: string;
  roofingDetails: string;
  challenges: string;
  designFeatures: string[];
  blueprintImage: string;
  blueprintCaption: string;
  interiorHighlight: string;
  testimonial: string;
  testimonialAuthor: string;
}

export const portfolioProjects: PortfolioProject[] = [
  {
    id: "summit-ridge-estate",
    title: "Summit Ridge Estate",
    location: "Crested Butte, CO",
    year: 2023,
    clients: "Michael & Sarah T.",
    image: images.gallery1,
    category: "metal",
    roofType: "Standing Seam Metal — Weathered Bronze",
    sqft: 4800,
    homeSqft: 6200,
    bedrooms: 5,
    bathrooms: 5,
    architect: "Berglund Architects, Crested Butte",
    duration: "14 weeks",
    elevation: "9,100 ft",
    tagline: "A timber-frame masterpiece crowned with bronze standing seam",
    overview: "Perched on a ridge overlooking the East River Valley, the Summit Ridge Estate is a 6,200 sq ft timber-frame residence that demanded a roof system capable of handling 300+ inches of annual snowfall while complementing the home's organic mountain aesthetic.",
    story: "Michael and Sarah T. had spent fifteen years vacationing in Crested Butte before deciding to build their forever home. They envisioned a residence that would feel like it grew from the mountainside itself — massive Douglas fir timbers, locally quarried stone, and a roof that would age gracefully alongside the surrounding aspens. Working with Berglund Architects, the couple designed a home with seven distinct roof planes, each requiring precise engineering to handle Crested Butte's legendary snow loads. Alpine Peak Roofing was brought in during the design phase to consult on material selection and structural requirements. The result is a 4,800 sq ft standing seam metal roof in weathered bronze that catches the golden hour light and mirrors the autumn aspen groves below.",
    roofingDetails: "The roof system features 24-gauge Galvalume standing seam panels with a custom weathered bronze finish, installed over a fully ventilated cold-roof assembly. The cold-roof design — with a 2-inch air gap between the insulation and roof deck — prevents ice damming at this elevation. Snow guards were strategically placed above all entry points, walkways, and the outdoor living area. The complex geometry required 47 custom-fabricated transition pieces at valleys and hips.",
    challenges: "The primary challenge was the home's 9,100-foot elevation and the steep 12:12 pitch on the main gables. All materials had to be helicoptered to the site during the final phase due to spring road closures. The crew worked in shifts to complete the installation before the first September snowfall, finishing with just 11 days to spare.",
    designFeatures: ["Seven distinct roof planes with varying pitches", "Custom copper snow guards at all entry points", "Integrated gutter heating system", "Cold-roof ventilation assembly for ice dam prevention", "Hidden fastener system for clean aesthetic"],
    blueprintImage: images.blueprintFloorplan,
    blueprintCaption: "Main floor plan showing the open great room concept with vaulted ceilings requiring specialized roof framing",
    interiorHighlight: "The great room features a 32-foot vaulted ceiling with exposed timber trusses, anchored by a floor-to-ceiling moss rock fireplace. The gourmet kitchen includes a 48-inch Wolf range, Sub-Zero refrigeration, and a 12-foot waterfall-edge island in honed Montana granite.",
    testimonial: "Alpine Peak didn't just install our roof — they helped us design it. Their input during the architectural phase saved us from costly mistakes and the result is beyond what we imagined.",
    testimonialAuthor: "Michael T., Homeowner",
  },
  {
    id: "elk-meadow-lodge",
    title: "Elk Meadow Lodge",
    location: "Telluride, CO",
    year: 2022,
    clients: "James & Patricia W.",
    image: images.gallery2,
    category: "residential",
    roofType: "GAF Timberline HDZ — Charcoal",
    sqft: 5200,
    homeSqft: 7100,
    bedrooms: 6,
    bathrooms: 7,
    architect: "Sante Architects, Telluride",
    duration: "16 weeks",
    elevation: "8,750 ft",
    tagline: "Where Telluride's box canyon meets architectural excellence",
    overview: "The Elk Meadow Lodge is a 7,100 sq ft mountain retreat nestled in a meadow just outside Telluride's historic district. The home's complex roofline — with nine distinct planes — required meticulous planning to ensure every valley, hip, and ridge performed flawlessly under the San Juan Mountains' extreme weather.",
    story: "James and Patricia W. are retired physicians who fell in love with Telluride during a medical conference twenty years ago. When they finally acquired a 3-acre parcel overlooking the valley, they wanted a home that honored the region's mining heritage while providing every modern comfort. Sante Architects designed a lodge-style residence with reclaimed timber, hand-laid stone, and expansive glass to frame the iconic box canyon views. The roofing challenge was significant: nine roof planes, three dormers, two chimneys, and a covered porte-cochère all needed to work as a unified system. Alpine Peak's team spent three weeks on-site before installation, mapping every detail with laser precision.",
    roofingDetails: "We installed GAF Timberline HDZ architectural shingles in Charcoal with the LayerLock technology for maximum wind resistance — critical at this elevation where gusts regularly exceed 80 mph. The system includes GAF Cobra Snow Country ridge vent, StormGuard leak barrier on all eaves and valleys, and a complete GAF Golden Pledge warranty. Custom copper flashing was fabricated on-site for all chimney and dormer intersections.",
    challenges: "Telluride's building codes require strict adherence to historic district guidelines, even for properties on the outskirts. The color palette had to be approved by the architectural review board. Additionally, the home's remote location meant all materials were staged at a base camp and transported by ATV to the build site.",
    designFeatures: ["Nine distinct roof planes with precision-cut valleys", "Custom copper chimney flashing and counter-flashing", "GAF Golden Pledge lifetime warranty", "Integrated ice and water shield on all vulnerable areas", "Color-matched ventilation system"],
    blueprintImage: images.blueprintKitchen,
    blueprintCaption: "Gourmet kitchen design with professional-grade appliances and mountain view breakfast nook",
    interiorHighlight: "The chef's kitchen features a La Cornue range imported from France, a 14-foot island with seating for six, and a walk-in pantry with custom cedar shelving. The adjacent great room has a 28-foot stone fireplace with a reclaimed railroad tie mantel.",
    testimonial: "We interviewed five roofing companies. Alpine Peak was the only one that came to the site, studied the terrain, and presented a detailed plan before we even discussed pricing. That's the kind of professionalism that matters.",
    testimonialAuthor: "Dr. James W., Homeowner",
  },
  {
    id: "powder-ridge-chalet",
    title: "Powder Ridge Chalet",
    location: "Vail, CO",
    year: 2023,
    clients: "Robert & Elizabeth M.",
    image: images.gallery3,
    category: "metal",
    roofType: "Standing Seam Metal — Matte Black",
    sqft: 3600,
    homeSqft: 4800,
    bedrooms: 4,
    bathrooms: 4,
    architect: "Triumph Mountain Properties, Vail",
    duration: "10 weeks",
    elevation: "8,400 ft",
    tagline: "Ski-in luxury with a roof engineered for Vail's legendary snowfall",
    overview: "The Powder Ridge Chalet sits slopeside in Vail's exclusive Lionshead area, where the roof must handle not just natural snowfall but the additional load from snowmaking operations on the adjacent run. This 4,800 sq ft chalet required a roof system that was equal parts engineering marvel and architectural statement.",
    story: "Robert and Elizabeth M. wanted their Vail chalet to be a gathering place for their extended family — a home where three generations could ski out the back door and return to a warm fire. The design called for dramatic A-frame elements with walls of glass facing the slopes, creating a roof geometry that was as challenging as it was beautiful. Alpine Peak worked closely with the structural engineer to design a roof system that could handle a 120 psf snow load while maintaining the sleek, modern aesthetic the owners desired.",
    roofingDetails: "The matte black standing seam metal roof uses 22-gauge steel panels with a Kynar 500 finish for superior color retention at altitude. The system features a heated roof edge to prevent ice dam formation, integrated snow retention bars rated for 120 psf, and concealed fasteners throughout. A secondary waterproofing membrane covers 100% of the roof deck as an additional safeguard.",
    challenges: "Working on an active ski slope presented unique logistics challenges. All installation had to occur during the summer construction window, and materials were transported via the resort's maintenance roads. The steep 14:12 pitch on the main A-frame required specialized safety equipment and anchor systems for the crew.",
    designFeatures: ["22-gauge steel with Kynar 500 finish", "Heated roof edge system", "Snow retention rated for 120 psf", "100% secondary waterproofing membrane", "Concealed fastener system throughout"],
    blueprintImage: images.blueprintTheater,
    blueprintCaption: "Home theater design with tiered seating and Dolby Atmos surround sound system",
    interiorHighlight: "The lower level features a dedicated home theater with tiered seating for 12, a 150-inch 4K laser projector, Dolby Atmos surround sound, acoustic wall treatments, and a wet bar with draft beer system. The theater room was designed as a retreat for après-ski entertainment.",
    testimonial: "Our roof handles more snow than most buildings in Colorado. Alpine Peak engineered a system that gives us complete peace of mind, even during the heaviest storms.",
    testimonialAuthor: "Robert M., Homeowner",
  },
  {
    id: "aspen-grove-retreat",
    title: "Aspen Grove Retreat",
    location: "Aspen, CO",
    year: 2021,
    clients: "David & Catherine L.",
    image: images.heroResidential,
    category: "slate",
    roofType: "Vermont Black Slate — Hand-Split",
    sqft: 6100,
    homeSqft: 8500,
    bedrooms: 7,
    bathrooms: 8,
    architect: "Rowland + Broughton Architecture, Aspen",
    duration: "22 weeks",
    elevation: "7,900 ft",
    tagline: "Hand-split Vermont slate on Aspen's most distinguished address",
    overview: "The Aspen Grove Retreat is an 8,500 sq ft estate on Red Mountain that required a roofing material worthy of its $18 million price tag. Hand-split Vermont black slate was selected for its timeless beauty and 100+ year lifespan, making it the most prestigious roofing project in Alpine Peak's history.",
    story: "David and Catherine L. are art collectors who divide their time between Manhattan and Aspen. Their vision was a home that felt like a European country estate transplanted to the Rockies — with the craftsmanship to match. Every detail was curated, from the hand-forged iron railings to the imported Italian marble. The roof was no exception. They specified hand-split Vermont black slate, sourced from a single quarry to ensure color consistency across the entire 6,100 sq ft roof surface. Alpine Peak sent a team to the quarry in Vermont to personally inspect and select the slate before it was shipped to Colorado.",
    roofingDetails: "Each slate tile was hand-selected and sorted by thickness before installation on a reinforced roof deck designed to support the 15 psf dead load. Copper flashing, valleys, and ridge caps were custom-fabricated by a master coppersmith. The installation followed traditional English slate-laying patterns with graduated courses — thicker slates at the eaves transitioning to thinner slates at the ridge. All fasteners are copper ring-shank nails.",
    challenges: "The sheer weight of natural slate required structural reinforcement of the roof framing — an additional $180,000 in engineering and materials. Each slate tile had to be individually inspected for soundness by tapping (the 'ring test') before installation. The 22-week timeline was the longest single-roof project in our history, but the result is a roof that will outlast the next three generations.",
    designFeatures: ["Hand-split Vermont black slate from single quarry", "Custom copper valleys, flashing, and ridge caps", "Traditional English graduated course pattern", "Reinforced roof framing for 15 psf dead load", "Copper ring-shank nail fasteners throughout"],
    blueprintImage: images.blueprintBathroom,
    blueprintCaption: "Master bathroom suite with freestanding soaking tub, dual-head walk-in shower, and heated floors",
    interiorHighlight: "The master suite occupies the entire east wing with a private balcony overlooking Aspen Mountain. The bathroom features a freestanding Waterworks soaking tub, a walk-in steam shower with dual rain heads, heated Calacatta marble floors, and a custom double vanity with vessel sinks.",
    testimonial: "We've built homes on three continents. Alpine Peak's attention to detail and respect for traditional craftsmanship is on par with the finest European artisans we've worked with.",
    testimonialAuthor: "David L., Homeowner",
  },
  {
    id: "winter-creek-cabin",
    title: "Winter Creek Cabin",
    location: "Winter Park, CO",
    year: 2024,
    clients: "Thomas & Jennifer K.",
    image: images.residentialWork,
    category: "residential",
    roofType: "GAF Timberline HDZ — Barkwood",
    sqft: 2800,
    homeSqft: 3200,
    bedrooms: 3,
    bathrooms: 3,
    architect: "Mountain Architecture Design Group",
    duration: "8 weeks",
    elevation: "9,000 ft",
    tagline: "A cozy mountain cabin with a roof built for Colorado's toughest winters",
    overview: "The Winter Creek Cabin proves that premium roofing isn't reserved for mega-mansions. This 3,200 sq ft cabin in Winter Park's Fraser Valley was designed as a year-round family retreat, and the owners wanted a roof that would perform at 9,000 feet without breaking the budget.",
    story: "Thomas and Jennifer K. are Denver-based teachers who saved for a decade to build their mountain getaway. They wanted a home that was warm, inviting, and built to last — without the eight-figure price tag of Aspen or Vail. Working with a local architect, they designed a classic mountain cabin with modern efficiency. Alpine Peak was recommended by their builder, and we approached this project with the same care and precision we bring to our largest estates. The Barkwood color was selected to complement the home's natural wood siding and blend with the surrounding pine forest.",
    roofingDetails: "The GAF Timberline HDZ system in Barkwood includes full StormGuard ice and water shield on all eaves, valleys, and around all penetrations. Cobra Snow Country ridge vents provide year-round ventilation, and the system carries GAF's Golden Pledge warranty. We also installed a custom copper chimney cap and cricket to prevent snow and ice buildup behind the stone chimney.",
    challenges: "The Fraser Valley is one of the coldest spots in Colorado, with temperatures regularly dropping below -20°F. All adhesives and sealants had to be rated for extreme cold application. We scheduled the installation for late August to ensure optimal conditions, and the crew completed the project two days ahead of schedule.",
    designFeatures: ["Full ice and water shield coverage", "Cobra Snow Country ventilation", "Custom copper chimney cap and cricket", "Cold-rated adhesives and sealants", "GAF Golden Pledge lifetime warranty"],
    blueprintImage: images.blueprintKitchen,
    blueprintCaption: "Open-concept kitchen design optimized for family gatherings with mountain views",
    interiorHighlight: "The open-concept kitchen and living area features a wood-burning fireplace with a reclaimed barn wood mantel, butcher block countertops, a farmhouse sink, and a breakfast bar overlooking the forest. The design prioritizes warmth and functionality over flash.",
    testimonial: "We're not millionaires, but Alpine Peak treated us like we were. Same crew, same quality, same attention to detail. Our little cabin has the best roof in the valley.",
    testimonialAuthor: "Jennifer K., Homeowner",
  },
  {
    id: "steamboat-ranch",
    title: "Steamboat Heritage Ranch",
    location: "Steamboat Springs, CO",
    year: 2022,
    clients: "William & Margaret H.",
    image: images.commercialWork,
    category: "residential",
    roofType: "Cedar Shake — Premium Grade",
    sqft: 5600,
    homeSqft: 5800,
    bedrooms: 5,
    bathrooms: 5,
    architect: "Four Points Design, Steamboat Springs",
    duration: "18 weeks",
    elevation: "6,700 ft",
    tagline: "Premium cedar shake honoring Steamboat's ranching heritage",
    overview: "The Steamboat Heritage Ranch is a 5,800 sq ft estate that pays homage to the region's cattle ranching roots while incorporating every modern luxury. The owners insisted on cedar shake — the traditional roofing material of the Yampa Valley — installed to the highest possible standard.",
    story: "William and Margaret H. are fourth-generation Coloradans whose family has ranched in the Yampa Valley since 1892. When they decided to build their retirement home on a portion of the original family ranch, there was never any question about the roof material. Cedar shake is part of the valley's DNA. But they wanted it done right — not the thin, machine-cut shakes found on most modern homes, but thick, hand-split premium grade shakes that would develop a beautiful silver patina over the decades. Alpine Peak sourced the cedar from a sustainable forestry operation in British Columbia and hand-sorted every shake for quality before installation.",
    roofingDetails: "The roof features #1 grade hand-split cedar shakes, 24 inches long with a 10-inch exposure, installed over skip sheathing for proper ventilation. A breathable synthetic underlayment provides secondary waterproofing while allowing the shakes to dry from both sides. All valleys are woven (not cut) for maximum water resistance, and copper step flashing is used at all wall intersections. The system includes a fire-retardant treatment rated to Class B.",
    challenges: "Cedar shake installation is inherently slower than other materials — each shake must be individually placed, spaced, and fastened. The 18-week timeline reflected the meticulous hand-craftsmanship required. Additionally, the fire-retardant treatment had to be applied in controlled conditions, requiring a temporary shelter over each section during treatment.",
    designFeatures: ["#1 grade hand-split cedar shakes, 24-inch", "Woven valleys for superior water resistance", "Breathable synthetic underlayment", "Class B fire-retardant treatment", "Copper step flashing at all intersections"],
    blueprintImage: images.blueprintFloorplan,
    blueprintCaption: "Main floor plan showing the wraparound porch and connection to the guest house and barn",
    interiorHighlight: "The great room features a 20-foot ceiling with hand-hewn timber beams salvaged from a century-old barn in Hayden. The kitchen includes a commercial-grade Thermador range, custom alder cabinetry, and a 10-foot island with seating for eight. French doors open to a covered porch overlooking the Yampa River.",
    testimonial: "Our family has been in this valley for over 130 years. Alpine Peak understood what this home means to us and delivered a roof that honors our heritage while protecting our future.",
    testimonialAuthor: "William H., Homeowner",
  },
  {
    id: "telluride-copper-lodge",
    title: "Telluride Copper Lodge",
    location: "Telluride, CO",
    year: 2024,
    clients: "Andrew & Victoria S.",
    image: images.portfolio7,
    category: "metal",
    roofType: "Standing Seam Copper — Natural Patina",
    sqft: 5400,
    homeSqft: 7800,
    bedrooms: 6,
    bathrooms: 7,
    architect: "Berglund Architects, Telluride",
    duration: "20 weeks",
    elevation: "8,800 ft",
    tagline: "A copper crown in Telluride's box canyon",
    overview: "The Telluride Copper Lodge is a 7,800 sq ft timber-frame masterpiece featuring a standing seam copper roof that has already begun developing the distinctive green patina that will deepen over the coming decades. Set against the dramatic San Juan Mountains, this is one of the most photographed homes in Telluride.",
    story: "Andrew and Victoria S. are tech entrepreneurs who wanted their Telluride home to be a legacy property — something their grandchildren would inherit. They chose copper specifically because it's the only roofing material that actually becomes more beautiful with age. The home's massive timber frame, with Douglas fir beams up to 36 inches in diameter, required a roof material with equal gravitas. Alpine Peak's master installers spent 20 weeks hand-forming and installing each copper panel, creating a roof that is as much a work of art as it is a weather barrier.",
    roofingDetails: "The roof features 20-oz copper standing seam panels with double-lock seams for maximum weather resistance. All copper was sourced from a single mill to ensure consistent alloy composition and uniform patina development. Custom copper gutters, downspouts, and snow guards were fabricated to match. The system includes a fully adhered ice and water shield membrane and a ventilated cold-roof assembly.",
    challenges: "Copper is significantly more expensive and difficult to work with than steel. Every cut, bend, and seam must be perfect because copper shows every imperfection. The 20-week timeline reflected the painstaking craftsmanship required. Temperature management during installation was critical — copper expands and contracts significantly, requiring precise allowances at every seam.",
    designFeatures: ["20-oz copper panels with double-lock seams", "Single-mill sourcing for uniform patina", "Custom copper gutters and downspouts", "Ventilated cold-roof assembly", "Hand-formed transition pieces at all intersections"],
    blueprintImage: images.blueprintKitchen,
    blueprintCaption: "Gourmet kitchen with professional-grade appliances, butler's pantry, and mountain view breakfast nook",
    interiorHighlight: "The kitchen features a 48-inch La Cornue range in custom copper finish to echo the roof, a 16-foot island with waterfall-edge quartzite, and a butler's pantry with wine refrigeration. The adjacent dining room seats 14 beneath a hand-forged iron chandelier.",
    testimonial: "Every morning I look up at our copper roof catching the sunrise and I'm reminded why we chose Alpine Peak. This isn't just a roof — it's the crown of our home.",
    testimonialAuthor: "Victoria S., Homeowner",
  },
  {
    id: "aspen-modern-retreat",
    title: "Aspen Modern Retreat",
    location: "Aspen, CO",
    year: 2025,
    clients: "Daniel & Sophia R.",
    image: images.portfolio8,
    category: "metal",
    roofType: "Zinc Standing Seam — Natural Matte",
    sqft: 3800,
    homeSqft: 5200,
    bedrooms: 4,
    bathrooms: 5,
    architect: "Studio B Architecture, Aspen",
    duration: "12 weeks",
    elevation: "8,200 ft",
    tagline: "Ultra-modern mountain architecture with a zinc crown",
    overview: "The Aspen Modern Retreat is a bold departure from traditional mountain architecture — a cantilevered glass-and-steel structure perched on a steep hillside with views of the Maroon Bells. The butterfly roof design in natural zinc creates a striking silhouette against the winter sky.",
    story: "Daniel and Sophia R. are architects themselves, based in Los Angeles, who wanted their Aspen home to challenge every convention of mountain design. No log beams, no river rock, no antler chandeliers. Instead, they envisioned a home that was unapologetically modern — concrete, steel, glass, and zinc. The butterfly roof design was both aesthetic and functional, channeling snowmelt to a central collection point for the home's greywater system. Alpine Peak embraced the challenge, working with the architects to develop a zinc roof system that would complement the home's minimalist aesthetic while performing in Aspen's harsh alpine environment.",
    roofingDetails: "The roof features pre-weathered zinc standing seam panels in a natural matte finish. Zinc was selected for its self-healing properties — minor scratches develop a protective patina that blends seamlessly with the surrounding surface. The butterfly roof geometry required custom-engineered drainage at the center valley, with heated channels to prevent ice buildup. All seams are soldered rather than mechanically locked for a cleaner appearance.",
    challenges: "The butterfly roof design creates an inverted valley at the center of the home — the opposite of conventional roof drainage. This required a custom-engineered heated gutter system at the low point with redundant overflow drains. The cantilevered sections of the home also created access challenges, requiring the crew to work from scaffolding suspended over a 40-foot drop.",
    designFeatures: ["Pre-weathered zinc with self-healing patina", "Butterfly roof with engineered central drainage", "Soldered seams for minimalist aesthetic", "Heated central valley gutter system", "Integrated with greywater collection system"],
    blueprintImage: images.blueprintBathroom,
    blueprintCaption: "Master bathroom with freestanding tub positioned for Maroon Bells views through floor-to-ceiling glass",
    interiorHighlight: "The master bathroom is a spa-like retreat with a freestanding Agape tub positioned before a floor-to-ceiling window framing the Maroon Bells. Heated concrete floors, a curbless walk-in shower with rainfall head, and custom walnut vanities complete the space.",
    testimonial: "As architects, we're our own worst clients. Alpine Peak not only met our exacting standards — they exceeded them. The zinc roof is the defining element of our home.",
    testimonialAuthor: "Daniel R., Architect & Homeowner",
  },
  {
    id: "yampa-valley-ranch",
    title: "Yampa Valley Ranch Estate",
    location: "Steamboat Springs, CO",
    year: 2023,
    clients: "Richard & Anne B.",
    image: images.portfolio9,
    category: "residential",
    roofType: "Cedar Shake — Premium Hand-Split",
    sqft: 7200,
    homeSqft: 6800,
    bedrooms: 5,
    bathrooms: 6,
    architect: "Kelly & Stone Architects, Steamboat Springs",
    duration: "16 weeks",
    elevation: "6,800 ft",
    tagline: "A sprawling ranch estate with hand-split cedar as far as the eye can see",
    overview: "The Yampa Valley Ranch Estate is a 6,800 sq ft single-story ranch home with a separate guest house and horse barn — all unified by matching premium hand-split cedar shake roofs totaling 7,200 sq ft of coverage. Set in a wildflower meadow along the Yampa River, this is Colorado ranching at its finest.",
    story: "Richard and Anne B. relocated from Dallas to fulfill a lifelong dream of living on a working cattle ranch. They purchased 160 acres along the Yampa River and commissioned a home that would feel rooted in the landscape — as if it had always been there. The sprawling single-story design with deep covered porches was inspired by historic Colorado ranch houses, but with every modern amenity hidden behind the rustic facade. The cedar shake roof was non-negotiable — Richard's grandfather had been a cedar shake roofer in Oregon, and the material held deep personal significance.",
    roofingDetails: "All three structures feature #1 grade hand-split cedar shakes from British Columbia, installed with a 10-inch exposure over skip sheathing. The main house, guest house, and barn roofs were installed sequentially to ensure color consistency across all structures. A breathable underlayment system allows the shakes to dry from both sides, extending their lifespan. All valleys are woven, and copper flashing is used throughout.",
    challenges: "The sheer scale of this project — 7,200 sq ft across three structures — made it one of the largest cedar shake installations in Steamboat Springs history. Coordinating the sequential installation across three buildings while maintaining color and quality consistency required meticulous planning and a dedicated crew of eight for the full 16-week duration.",
    designFeatures: ["7,200 sq ft of matching cedar shake across three structures", "Woven valleys on all buildings", "Copper flashing and custom chimney caps", "Fire-retardant treatment rated Class B", "Skip sheathing for optimal ventilation"],
    blueprintImage: images.blueprintFloorplan,
    blueprintCaption: "Ranch estate floor plan showing the main house, covered breezeway to guest house, and barn connection",
    interiorHighlight: "The great room features a 20-foot ceiling with hand-hewn timber trusses and a double-sided stone fireplace shared with the dining room. The kitchen opens to a covered porch with an outdoor kitchen, pizza oven, and views of the Yampa River and the Flat Tops Wilderness beyond.",
    testimonial: "My grandfather would have been proud. Alpine Peak installed our cedar shake roof with the same care and craftsmanship he practiced 60 years ago. This is a roof built by people who love what they do.",
    testimonialAuthor: "Richard B., Homeowner",
  },
  {
    id: "vail-chateau",
    title: "Château de Vail",
    location: "Vail, CO",
    year: 2022,
    clients: "Philippe & Marie-Claire D.",
    image: images.portfolio10,
    category: "slate",
    roofType: "Vermont Slate — Deep Charcoal with Copper Accents",
    sqft: 5800,
    homeSqft: 9200,
    bedrooms: 7,
    bathrooms: 9,
    architect: "RKD Architects, Vail",
    duration: "24 weeks",
    elevation: "8,300 ft",
    tagline: "A European château with a slate crown worthy of the French countryside",
    overview: "Château de Vail is a 9,200 sq ft European-inspired estate that required the most technically demanding slate roof installation in Alpine Peak's history. The home features a steep-pitched main roof, a conical turret, copper dormers, and ornate copper gutters — all requiring master-level craftsmanship.",
    story: "Philippe and Marie-Claire D. are French expatriates who wanted their Vail home to evoke the châteaux of the Loire Valley while embracing the Rocky Mountain setting. The design features cream stucco walls, arched windows, a circular turret with a conical slate roof, and a formal courtyard with fountain. The slate roof was essential to the vision — no other material could achieve the authentic European character they demanded. Alpine Peak assembled a specialized crew including a master slater trained in traditional European techniques to ensure every detail was historically accurate.",
    roofingDetails: "The roof features Vermont unfading black slate in graduated courses, with thicker 3/8-inch slates at the eaves tapering to 1/4-inch at the ridge. The conical turret roof required each slate to be individually shaped to follow the curve — over 800 custom-cut pieces. All flashing, valleys, ridge caps, and dormer cheeks are fabricated from 20-oz copper. The ornate copper gutters feature a custom half-round profile with decorative brackets.",
    challenges: "The conical turret was the most challenging element — a circular slate roof requires every piece to be individually measured, cut, and fitted. Our master slater spent six weeks on the turret alone. The steep 16:12 pitch on the main roof required permanent roof anchors for maintenance access. The 24-week timeline made this our longest residential project to date.",
    designFeatures: ["Vermont unfading black slate in graduated courses", "800+ custom-cut slates for conical turret", "20-oz copper flashing, valleys, and ridge caps", "Ornate half-round copper gutters with decorative brackets", "Permanent roof anchors for maintenance access"],
    blueprintImage: images.blueprintTheater,
    blueprintCaption: "Wine cellar and tasting room design in the château's lower level",
    interiorHighlight: "The lower level houses a temperature-controlled wine cellar with capacity for 2,000 bottles, a tasting room with barrel-vaulted ceiling, and a billiards room with hand-painted ceiling murals. The formal dining room seats 16 beneath a Baccarat crystal chandelier.",
    testimonial: "We have homes in Paris and Provence. Alpine Peak's craftsmanship on our slate roof rivals the finest artisans in France. C'est magnifique.",
    testimonialAuthor: "Philippe D., Homeowner",
  },
  {
    id: "breckenridge-ski-lodge",
    title: "Peak 8 Ski Lodge",
    location: "Breckenridge, CO",
    year: 2024,
    clients: "Christopher & Amanda F.",
    image: images.portfolio11,
    category: "residential",
    roofType: "GAF Timberline HDZ — Weathered Wood",
    sqft: 4200,
    homeSqft: 5500,
    bedrooms: 5,
    bathrooms: 5,
    architect: "Breckenridge Associates Architects",
    duration: "10 weeks",
    elevation: "9,600 ft",
    tagline: "Ski-in/ski-out living at Colorado's highest elevation",
    overview: "The Peak 8 Ski Lodge sits at 9,600 feet — the highest elevation project in Alpine Peak's portfolio. This 5,500 sq ft ski-in/ski-out home required a roof system engineered for the most extreme conditions in Colorado: 300+ inches of annual snowfall, 100+ mph wind gusts, and UV exposure 40% higher than sea level.",
    story: "Christopher and Amanda F. are avid skiers who wanted to live as close to the slopes as physically possible. Their lot on Peak 8 is literally steps from the chairlift, which meant the home had to be designed to coexist with the ski area's operations — including snowmaking, grooming, and the constant foot traffic of skiers passing by. The roof needed to handle not just natural snowfall but the additional accumulation from snowmaking operations on the adjacent run. Alpine Peak designed a system that could handle a 150 psf snow load — 50% above code minimum — with a heated driveway and entry to ensure safe access year-round.",
    roofingDetails: "The GAF Timberline HDZ in Weathered Wood was selected for its Class 4 impact resistance — essential in a hail-prone area. The system includes full StormGuard ice and water shield on the entire roof deck (not just eaves and valleys), Cobra Snow Country ridge vents, and a custom snow retention system rated for 150 psf. Heated roof edges prevent ice dam formation, and all penetrations are triple-flashed.",
    challenges: "At 9,600 feet, the construction season is brutally short — roughly mid-June through mid-September. The crew worked 10-hour days, six days a week to complete the installation in the available window. Material delivery was coordinated with the ski resort's summer maintenance schedule to avoid conflicts with mountain bike trails and hiking paths.",
    designFeatures: ["Full-deck ice and water shield coverage", "Snow retention rated for 150 psf", "Heated roof edges and entry areas", "Class 4 impact-resistant shingles", "Triple-flashed penetrations"],
    blueprintImage: images.blueprintBathroom,
    blueprintCaption: "Master bathroom with steam shower and heated floors for post-ski recovery",
    interiorHighlight: "The mudroom features a custom ski storage system with boot dryers for 10 pairs, a gear drying room with commercial ventilation, and a boot wash station. The hot tub deck overlooks Peak 8 with views of the Continental Divide.",
    testimonial: "We can literally ski to our front door. Alpine Peak built a roof that handles everything Breckenridge throws at it — and that's saying something at 9,600 feet.",
    testimonialAuthor: "Christopher F., Homeowner",
  },
  {
    id: "durango-river-house",
    title: "Animas River Craftsman",
    location: "Durango, CO",
    year: 2023,
    clients: "Mark & Susan G.",
    image: images.portfolio12,
    category: "residential",
    roofType: "GAF Timberline HDZ — Weathered Wood",
    sqft: 4600,
    homeSqft: 5400,
    bedrooms: 5,
    bathrooms: 4,
    architect: "Reynolds Ash + Associates, Durango",
    duration: "12 weeks",
    elevation: "6,500 ft",
    tagline: "Mountain craftsman elegance overlooking the Animas River",
    overview: "The Animas River Craftsman is a 5,400 sq ft mountain craftsman home perched on a hillside overlooking the Animas River valley with panoramic views of the La Plata Mountains. The complex multi-level roofline with multiple gables, dormers, and a covered outdoor living area required precision engineering and flawless execution.",
    story: "Mark and Susan G. are Durango natives who spent 30 years building their careers before returning to build their dream home on a hillside they'd admired since childhood. They wanted a home that honored Durango's craftsman architectural tradition — exposed timber, river rock, and honest materials — while incorporating modern performance standards. The roofline was designed to echo the surrounding mountain ridges, with multiple gables stepping down the hillside to follow the natural terrain. Alpine Peak's team worked closely with the architect to ensure every roof plane drained properly and every intersection was sealed against Durango's intense summer thunderstorms.",
    roofingDetails: "The GAF Timberline HDZ in Weathered Wood was chosen to complement the home's natural wood and stone exterior. The system features full StormGuard coverage on all valleys, eaves, and around the three stone chimneys. Custom copper chimney caps and crickets prevent water intrusion, and the ventilation system was designed to handle the significant temperature differentials between Durango's hot summers and cold winters.",
    challenges: "The hillside location created significant access challenges — materials had to be staged at the top of the property and transported down to the various roof levels. The multi-level design meant the crew was essentially working on five separate roofs that all had to integrate seamlessly. Durango's summer monsoon season also required careful scheduling to avoid afternoon thunderstorms.",
    designFeatures: ["Multi-level roofline following natural terrain", "Custom copper chimney caps and crickets", "Full StormGuard coverage on all critical areas", "Ventilation designed for extreme temperature differentials", "Three-car garage with matching roofline"],
    blueprintImage: images.blueprintKitchen,
    blueprintCaption: "Gourmet kitchen with professional range, custom cabinetry, and river valley views",
    interiorHighlight: "The covered outdoor living area features a stone fireplace with a reclaimed timber mantel, a built-in grill and pizza oven, and a dining area for 10 — all with unobstructed views of the Animas River and the La Plata Mountains. The indoor kitchen features a 48-inch Thermador range and custom alder cabinetry.",
    testimonial: "We grew up looking at this hillside, dreaming about building here someday. Alpine Peak helped make that dream real with a roof that's as beautiful as the view.",
    testimonialAuthor: "Susan G., Homeowner",
  },
];
