// Alpine Peak Roofing - Comprehensive Services Data
// Each service has its own indexable page for SEO/AEO optimization

export interface ServiceDetail {
  slug: string;
  category: 'residential' | 'commercial';
  title: string;
  shortTitle: string;
  tagline: string;
  description: string;
  image: string;
  heroImage: string;
  icon: string;
  features: string[];
  process: { step: string; description: string }[];
  benefits: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
  materials?: string[];
  metaDescription: string;
  relatedServices: string[];
}

export const residentialServices: ServiceDetail[] = [
  {
    slug: 'complete-roof-replacement',
    category: 'residential',
    title: 'Complete Roof Replacement',
    shortTitle: 'Roof Replacement',
    tagline: 'Full tear-off and replacement with premium materials — from permits to final inspection.',
    description: 'When repairs are no longer sufficient, a complete roof replacement is the most effective way to protect your home and increase its value. Alpine Peak Roofing specializes in full tear-off and replacement projects for Colorado mountain homes, handling everything from initial assessment and permitting to material selection, installation, and final inspection. Our team understands the unique demands of high-altitude roofing — from extreme UV exposure at 9,000+ feet to heavy snow loads exceeding 60 pounds per square foot. We work with premium materials engineered for mountain environments, including standing seam metal, architectural shingles rated for 130+ mph winds, and natural slate. Every replacement project includes a comprehensive underlayment system with ice and water shield protection, proper ventilation assessment, and a transferable manufacturer warranty backed by our own craftsmanship guarantee.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-roof-replacement-Y79yf9ED3QPbh5Di4irMCE.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-roof-replacement-XSckuKw7uyowGAhPcuLJqx.png',
    icon: 'Layers',
    features: [
      'Full tear-off of existing roofing materials down to the deck',
      'Comprehensive deck inspection and repair',
      'Premium ice and water shield underlayment system',
      'High-performance ventilation assessment and upgrade',
      'Standing seam metal, architectural shingle, or natural slate options',
      'All permits, inspections, and code compliance handled',
      'Complete cleanup with magnetic nail sweep',
      'Transferable manufacturer warranty plus craftsmanship guarantee',
    ],
    process: [
      { step: 'Free Inspection & Assessment', description: 'Our certified inspectors evaluate your existing roof condition, deck integrity, ventilation, and insulation. We document everything with photos and measurements.' },
      { step: 'Material Selection & Design', description: 'Choose from our curated selection of premium roofing materials. We help you select the best option for your home\'s architecture, local climate, and budget.' },
      { step: 'Permitting & Scheduling', description: 'We handle all building permits and HOA approvals. Your project is scheduled with weather contingencies built in for mountain conditions.' },
      { step: 'Tear-Off & Deck Prep', description: 'Complete removal of old roofing materials. Thorough inspection and repair of the roof deck, replacement of any damaged sheathing.' },
      { step: 'Installation', description: 'Professional installation by our experienced mountain roofing crews. Ice and water shield, underlayment, flashing, and premium roofing materials installed to manufacturer specifications.' },
      { step: 'Final Inspection & Warranty', description: 'Comprehensive quality inspection, cleanup, and magnetic nail sweep. You receive all warranty documentation and a maintenance guide.' },
    ],
    benefits: [
      { title: 'Increased Home Value', description: 'A new roof typically returns 60-70% of its cost in home value and makes your property significantly more attractive to buyers.' },
      { title: 'Energy Efficiency', description: 'Modern roofing materials with proper ventilation can reduce heating and cooling costs by up to 25% in mountain climates.' },
      { title: 'Peace of Mind', description: 'Eliminate ongoing repair costs and worry with a complete system backed by manufacturer and craftsmanship warranties.' },
      { title: 'Insurance Compliance', description: 'Many insurance companies offer premium discounts for new, impact-resistant roofing systems rated for Colorado weather.' },
    ],
    faqs: [
      { question: 'How long does a complete roof replacement take?', answer: 'Most residential replacements take 3-7 days depending on size, complexity, and weather. Mountain homes with complex rooflines or steep pitches may take longer. We provide a detailed timeline during your consultation.' },
      { question: 'Can you replace my roof in winter?', answer: 'Yes, we perform year-round installations. Metal roofing can be installed in any season. Shingle installations require temperatures above 40°F for proper adhesive activation. We monitor weather windows carefully.' },
      { question: 'What happens to my old roofing materials?', answer: 'We handle all disposal responsibly. Asphalt shingles are recycled when possible, and all debris is removed from your property. Our cleanup includes a magnetic nail sweep of your entire yard and driveway.' },
      { question: 'Do I need to be home during the replacement?', answer: 'No, but we recommend being available for the initial start and final walkthrough. We communicate progress daily via text and photos.' },
    ],
    materials: ['Standing Seam Metal', 'Architectural Shingles', 'Natural Slate', 'Synthetic Slate', 'Cedar Shake', 'Copper'],
    metaDescription: 'Complete roof replacement services in Colorado mountains. Alpine Peak Roofing handles full tear-off, premium material installation, permits, and inspections. Free estimates available.',
    relatedServices: ['roof-repairs', 'new-construction', 'ventilation'],
  },
  {
    slug: 'roof-repairs',
    category: 'residential',
    title: 'Roof Repairs',
    shortTitle: 'Roof Repairs',
    tagline: 'Expert repair services for leaks, missing shingles, flashing issues, and storm damage.',
    description: 'Colorado mountain weather is relentless — from summer hailstorms and high winds to heavy snow loads and ice dams in winter. Alpine Peak Roofing provides expert repair services to address damage quickly and prevent small problems from becoming expensive emergencies. Our repair specialists are trained to diagnose the root cause of leaks, not just patch symptoms. Whether you\'re dealing with wind-lifted shingles, deteriorated flashing around chimneys and skylights, ice dam damage, or impact from falling branches, we deliver permanent solutions using the same premium materials we use in our full installations. We offer priority scheduling for active leaks and emergency situations, with most repairs completed within 24-48 hours of assessment.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-roof-repairs-BEmx6rypETS3Ah8VheMV6V.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-roof-repairs-foBPKXihjuA3FM69sKRPB2.png',
    icon: 'Wrench',
    features: [
      'Leak detection and permanent repair',
      'Shingle replacement and re-sealing',
      'Chimney and skylight flashing repair',
      'Ice dam damage remediation',
      'Wind and hail damage repair',
      'Valley and ridge cap restoration',
      'Pipe boot and vent replacement',
      'Emergency tarping and temporary protection',
    ],
    process: [
      { step: 'Damage Assessment', description: 'Thorough inspection to identify all damage points and underlying causes. We check for hidden moisture damage using infrared scanning when needed.' },
      { step: 'Detailed Estimate', description: 'Transparent pricing with photos documenting all identified issues. We explain what needs immediate repair versus what can be monitored.' },
      { step: 'Material Matching', description: 'We source materials that match your existing roof as closely as possible for a seamless repair that doesn\'t look patched.' },
      { step: 'Professional Repair', description: 'Our experienced technicians complete repairs using manufacturer-approved methods and premium materials built for mountain conditions.' },
      { step: 'Quality Verification', description: 'Water testing and inspection to confirm the repair is watertight. We document the completed work with photos for your records.' },
    ],
    benefits: [
      { title: 'Prevent Costly Damage', description: 'A small leak can cause thousands in structural damage if left unaddressed. Timely repairs protect your home\'s structure and interior.' },
      { title: 'Extend Roof Life', description: 'Regular maintenance and prompt repairs can extend your roof\'s lifespan by 5-10 years beyond its rated life.' },
      { title: 'Insurance Documentation', description: 'We provide detailed documentation of damage and repairs that satisfies insurance requirements for claims.' },
      { title: 'Fast Response', description: 'Priority scheduling for active leaks with most repairs completed within 24-48 hours of assessment.' },
    ],
    faqs: [
      { question: 'How do I know if I need a repair or a full replacement?', answer: 'Generally, if damage is localized to one area and your roof is less than 15-20 years old, a repair is appropriate. If damage is widespread or your roof is aging, replacement may be more cost-effective. We\'ll give you an honest assessment.' },
      { question: 'Do you offer emergency repair services?', answer: 'Yes, we provide 24/7 emergency response for active leaks and storm damage. We can typically have a crew on-site within hours to provide temporary protection and schedule permanent repairs.' },
      { question: 'Will the repair match my existing roof?', answer: 'We go to great lengths to source matching materials. For older roofs where exact matches aren\'t available, we discuss options to ensure the repair blends as seamlessly as possible.' },
      { question: 'How long do roof repairs last?', answer: 'Our repairs are designed to be permanent solutions, not temporary patches. We use the same premium materials and techniques as our full installations, backed by our craftsmanship warranty.' },
    ],
    metaDescription: 'Expert roof repair services in Colorado mountains. Fix leaks, storm damage, missing shingles, and flashing issues. 24/7 emergency response. Alpine Peak Roofing.',
    relatedServices: ['complete-roof-replacement', 'gutter-systems', 'ventilation'],
  },
  {
    slug: 'new-construction',
    category: 'residential',
    title: 'New Construction Roofing',
    shortTitle: 'New Construction',
    tagline: 'Custom roofing solutions for new home builds, working closely with builders and architects.',
    description: 'Building a new home in Colorado\'s mountains is an exciting investment that deserves a roofing system designed specifically for your vision and your environment. Alpine Peak Roofing partners with homeowners, builders, and architects from the design phase to create roofing solutions that complement your home\'s architecture while providing maximum protection against mountain weather. We bring deep expertise in high-altitude construction requirements, including proper snow load engineering, ice dam prevention systems, and material selection optimized for UV exposure at elevation. Our team coordinates seamlessly with your general contractor to ensure the roofing phase integrates smoothly with the overall construction timeline. From simple gable designs to complex multi-level rooflines with dormers, valleys, and mixed materials, we deliver craftsmanship that matches the quality of your new home.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-new-construction-6hUXdCuZcgHguWXBCT75vh.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-new-construction-X3Ui3WXktkrzaf95ynrMKm.png',
    icon: 'HardHat',
    features: [
      'Design consultation with architects and builders',
      'Snow load engineering and structural analysis',
      'Premium material selection for mountain environments',
      'Complex multi-level roofline installation',
      'Integrated ice dam prevention systems',
      'Custom flashing and trim fabrication',
      'Coordination with general contractor timeline',
      'Full manufacturer warranty registration',
    ],
    process: [
      { step: 'Design Consultation', description: 'We review architectural plans and discuss material options, color selections, and special features. We advise on mountain-specific requirements like snow load ratings and ventilation.' },
      { step: 'Engineering Review', description: 'Our team verifies structural requirements for your chosen materials, including truss spacing, deck specifications, and load calculations for Colorado snow loads.' },
      { step: 'Material Procurement', description: 'We order materials with lead times factored into your construction schedule. Custom colors, specialty materials, and fabricated components are coordinated in advance.' },
      { step: 'Underlayment & Prep', description: 'Installation of premium underlayment system including ice and water shield in all valleys, eaves, and penetration areas. Proper ventilation channels established.' },
      { step: 'Roofing Installation', description: 'Expert installation of your chosen roofing system by our experienced mountain construction crews. We work efficiently to keep your project on schedule.' },
      { step: 'Integration & Completion', description: 'Final flashing, trim, gutter installation, and coordination with other trades. Comprehensive inspection and warranty documentation provided.' },
    ],
    benefits: [
      { title: 'Design Freedom', description: 'Choose from the widest range of premium materials and configurations. New construction allows for optimal roof design without compromise.' },
      { title: 'Proper Engineering', description: 'Your roof is engineered from the ground up for Colorado mountain conditions — no retrofitting or compromises.' },
      { title: 'Builder Coordination', description: 'We integrate seamlessly with your construction team, maintaining timeline and quality standards throughout.' },
      { title: 'Long-Term Value', description: 'A properly designed and installed new roof maximizes your home\'s value and minimizes lifetime maintenance costs.' },
    ],
    faqs: [
      { question: 'When should I involve Alpine Peak in my new build?', answer: 'Ideally during the design phase. Early involvement allows us to advise on structural requirements, material options, and design features that can save money and improve performance.' },
      { question: 'What materials do you recommend for new mountain homes?', answer: 'Standing seam metal is our top recommendation for mountain environments — it handles snow, wind, and UV better than any other material. We also install premium architectural shingles, natural slate, and cedar shake.' },
      { question: 'How do you coordinate with my general contractor?', answer: 'We establish a direct communication channel with your GC, attend relevant coordination meetings, and build weather contingencies into our scheduling to avoid delays.' },
      { question: 'Can you handle complex rooflines?', answer: 'Complex rooflines are our specialty. We regularly install roofs with 7-9 different planes, multiple dormers, valleys, and mixed material combinations on luxury mountain homes.' },
    ],
    materials: ['Standing Seam Metal', 'Copper Roofing', 'Natural Slate', 'Cedar Shake', 'Architectural Shingles', 'Zinc Panels'],
    metaDescription: 'New construction roofing for Colorado mountain homes. Custom design, premium materials, builder coordination. Alpine Peak Roofing works with architects and builders.',
    relatedServices: ['complete-roof-replacement', 'skylights-solar', 'gutter-systems'],
  },
  {
    slug: 'gutter-systems',
    category: 'residential',
    title: 'Gutter Systems',
    shortTitle: 'Gutter Systems',
    tagline: 'Seamless gutter installation, guards, and drainage solutions to protect your foundation.',
    description: 'A properly designed gutter system is essential for protecting your Colorado mountain home from water damage. With annual precipitation ranging from 20 to 40+ inches depending on elevation, plus significant snowmelt in spring, your gutters work harder than in most climates. Alpine Peak Roofing designs and installs complete gutter systems engineered for mountain conditions — from seamless aluminum and copper gutters to heated gutter systems that prevent ice dam formation. We assess your home\'s unique drainage needs, including roof area calculations, rainfall intensity, and ground slope, to size and position gutters and downspouts for optimal performance. Our gutter guard systems keep debris out while allowing maximum water flow, reducing maintenance in heavily treed mountain settings.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-gutter-systems-RxmxTFzuuKHDKg5RSNix4i.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-gutter-systems-cL9CSFVHeMX73uqkqRhQAa.png',
    icon: 'Droplets',
    features: [
      'Custom-fabricated seamless aluminum gutters',
      'Premium copper half-round gutter systems',
      'Heated gutter systems for ice dam prevention',
      'Gutter guard and leaf protection systems',
      'Downspout routing and underground drainage',
      'Box gutters for commercial-style applications',
      'Snow guard integration with gutter systems',
      'Annual maintenance and cleaning programs',
    ],
    process: [
      { step: 'Drainage Assessment', description: 'We evaluate your roof area, pitch, and local rainfall data to calculate proper gutter sizing. We assess ground drainage and identify optimal downspout locations.' },
      { step: 'System Design', description: 'Custom gutter layout designed for your home\'s architecture. We select materials, profiles, and colors that complement your roofing and trim.' },
      { step: 'On-Site Fabrication', description: 'Seamless gutters are fabricated on-site using our mobile forming equipment, ensuring perfect fit with no seams to leak.' },
      { step: 'Professional Installation', description: 'Gutters are installed with proper pitch for drainage, secure hidden hangers, and sealed connections. Downspouts are routed away from your foundation.' },
      { step: 'Testing & Protection', description: 'Water flow testing to verify proper drainage. Gutter guards installed if selected. We provide maintenance recommendations for your specific system.' },
    ],
    benefits: [
      { title: 'Foundation Protection', description: 'Properly channeled water prevents erosion, basement flooding, and foundation damage that can cost tens of thousands to repair.' },
      { title: 'Ice Dam Prevention', description: 'Heated gutter systems eliminate ice dams that cause roof leaks and gutter damage during Colorado winters.' },
      { title: 'Reduced Maintenance', description: 'Gutter guard systems dramatically reduce cleaning frequency, especially important for homes surrounded by pine trees.' },
      { title: 'Curb Appeal', description: 'Premium copper or color-matched aluminum gutters enhance your home\'s appearance while providing superior function.' },
    ],
    faqs: [
      { question: 'How often should gutters be cleaned in the mountains?', answer: 'Without guards, mountain homes typically need cleaning 2-4 times per year due to pine needles and debris. With our gutter guard systems, most homes only need annual inspection.' },
      { question: 'Are heated gutters worth the investment?', answer: 'In Colorado mountain communities, heated gutters are one of the best investments you can make. They prevent ice dams that cause thousands in roof and interior damage, and they eliminate dangerous icicle formation.' },
      { question: 'What size gutters do I need?', answer: 'Most mountain homes benefit from 6-inch gutters (vs. standard 5-inch) due to higher precipitation and snowmelt volumes. We calculate the exact sizing based on your roof area and local rainfall data.' },
      { question: 'Can you match my existing gutter color?', answer: 'Yes, we offer a wide range of factory-painted colors for aluminum gutters. Copper gutters develop a natural patina over time that many homeowners find beautiful.' },
    ],
    metaDescription: 'Professional gutter installation for Colorado mountain homes. Seamless aluminum, copper, heated systems, and gutter guards. Alpine Peak Roofing protects your foundation.',
    relatedServices: ['complete-roof-replacement', 'roof-repairs', 'ventilation'],
  },
  {
    slug: 'ventilation',
    category: 'residential',
    title: 'Roof Ventilation Systems',
    shortTitle: 'Ventilation',
    tagline: 'Proper attic ventilation systems to extend roof life and improve energy efficiency.',
    description: 'Proper attic ventilation is one of the most overlooked yet critical components of a healthy roofing system, especially in Colorado\'s extreme mountain climate. Without adequate ventilation, your attic traps heat in summer (accelerating shingle deterioration) and moisture in winter (causing ice dams, mold, and structural rot). Alpine Peak Roofing designs and installs balanced ventilation systems that maintain proper airflow from soffit to ridge, keeping your attic temperature close to outdoor ambient temperature year-round. This prevents ice dams by keeping the roof surface cold enough that snow doesn\'t melt and refreeze at the eaves. Our ventilation solutions include ridge vents, soffit vents, powered attic fans, and custom solutions for complex rooflines where standard approaches don\'t work. We also address existing ventilation problems, including blocked soffits, inadequate intake, and improperly installed bathroom and dryer vents.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-ventilation-ZCXQUGTKMFFUiHeZ43E4zj.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-ventilation-ErY4MrZ3zRnXVayVKG2vmp.png',
    icon: 'Wind',
    features: [
      'Balanced ridge and soffit ventilation systems',
      'Continuous ridge vent installation',
      'Soffit vent installation and repair',
      'Powered attic ventilation fans',
      'Bathroom and dryer vent re-routing',
      'Attic insulation assessment',
      'Ice dam prevention through proper ventilation',
      'Energy efficiency optimization',
    ],
    process: [
      { step: 'Ventilation Audit', description: 'We measure your attic\'s current ventilation ratio, check for blocked vents, assess insulation levels, and identify moisture or heat issues.' },
      { step: 'System Design', description: 'Based on your attic square footage and roof configuration, we design a balanced ventilation system that meets or exceeds building code requirements.' },
      { step: 'Intake Installation', description: 'Soffit vents or other intake vents are installed or upgraded to provide adequate fresh air intake at the lowest point of the attic.' },
      { step: 'Exhaust Installation', description: 'Ridge vents, roof vents, or powered fans are installed at the highest points to create natural convective airflow through the attic space.' },
      { step: 'Verification', description: 'We verify proper airflow, check for any obstructions, and ensure insulation isn\'t blocking vent channels. Temperature monitoring confirms the system is working.' },
    ],
    benefits: [
      { title: 'Ice Dam Prevention', description: 'Proper ventilation keeps the roof surface cold, preventing snowmelt that refreezes at eaves and causes damaging ice dams.' },
      { title: 'Extended Roof Life', description: 'Reducing attic heat in summer can extend shingle life by 20-30% by preventing premature aging from excessive heat.' },
      { title: 'Energy Savings', description: 'A properly ventilated attic reduces cooling costs in summer and prevents moisture buildup that degrades insulation effectiveness in winter.' },
      { title: 'Mold Prevention', description: 'Adequate airflow prevents moisture accumulation that leads to mold growth, wood rot, and structural damage in your attic.' },
    ],
    faqs: [
      { question: 'How do I know if my attic ventilation is inadequate?', answer: 'Signs include ice dams in winter, excessive heat in your upper floors in summer, visible moisture or frost in the attic, peeling exterior paint, and shingles that are aging prematurely. We offer free ventilation assessments.' },
      { question: 'Can ventilation be added to an existing roof?', answer: 'Yes, ridge vents, soffit vents, and powered fans can all be retrofitted to existing roofs. We often add ventilation improvements during repair or replacement projects.' },
      { question: 'Won\'t more ventilation make my house colder in winter?', answer: 'No. Proper ventilation only affects the attic space above your insulation. Your living space stays warm while the attic stays cold — which is exactly what prevents ice dams.' },
      { question: 'How much ventilation does my attic need?', answer: 'Building code requires 1 square foot of net free ventilation area per 150 square feet of attic floor space (or 1:300 with a vapor barrier). We calculate the exact requirement for your home.' },
    ],
    metaDescription: 'Professional roof ventilation systems for Colorado mountain homes. Prevent ice dams, extend roof life, and improve energy efficiency. Alpine Peak Roofing.',
    relatedServices: ['complete-roof-replacement', 'roof-repairs', 'skylights-solar'],
  },
  {
    slug: 'skylights-solar',
    category: 'residential',
    title: 'Skylights & Solar Integration',
    shortTitle: 'Skylights & Solar',
    tagline: 'Skylight installation and solar panel integration with proper waterproofing.',
    description: 'Colorado enjoys over 300 days of sunshine per year, making skylights and solar panels excellent investments for mountain homes. Alpine Peak Roofing specializes in integrating these features into your roofing system without compromising weatherproofing or structural integrity. Our skylight installations include VELUX and other premium brands, with options for fixed, vented, and solar-powered models that bring natural light deep into your home. For solar integration, we work with leading solar installers to ensure roof penetrations are properly flashed and sealed, and we can install solar-ready roofing systems on new construction projects. Every installation includes our comprehensive waterproofing system with custom-fabricated flashing, ensuring your skylights and solar panels perform flawlessly through Colorado\'s extreme weather cycles.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-skylights-solar-BQHFMpQLuBH7ebFNmyTKcc.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-skylights-solar-M47SFJsfY2k78TM8dy89qg.png',
    icon: 'Sun',
    features: [
      'Premium VELUX skylight installation',
      'Fixed, vented, and solar-powered options',
      'Tubular skylights for interior rooms',
      'Solar panel roof integration and flashing',
      'Solar-ready roofing for new construction',
      'Custom curb-mounted skylight solutions',
      'Skylight replacement and re-flashing',
      'Energy-efficient glazing options',
    ],
    process: [
      { step: 'Site Assessment', description: 'We evaluate your roof structure, orientation, and interior layout to determine optimal skylight placement for maximum natural light and solar exposure.' },
      { step: 'Product Selection', description: 'Choose from our range of premium skylights and solar integration options. We help you balance light, ventilation, energy efficiency, and budget.' },
      { step: 'Structural Preparation', description: 'Roof opening is carefully cut and framed to maintain structural integrity. Headers and supports are added as needed for larger openings.' },
      { step: 'Installation & Flashing', description: 'Skylight or solar mounting system is installed with our comprehensive flashing system. Every penetration is sealed with multiple layers of protection.' },
      { step: 'Interior Finishing', description: 'Light shaft is framed and finished to your specifications. Drywall, trim, and paint complete the interior appearance.' },
      { step: 'Testing & Warranty', description: 'Water testing confirms weathertight installation. Manufacturer warranty is registered and maintenance instructions provided.' },
    ],
    benefits: [
      { title: 'Natural Light', description: 'Skylights can increase natural light by up to 30% in rooms below, reducing the need for artificial lighting and improving mood and well-being.' },
      { title: 'Energy Savings', description: 'Solar-powered skylights with smart sensors automatically open for ventilation, reducing cooling costs. Solar panels generate clean energy year-round.' },
      { title: 'Home Value', description: 'Well-placed skylights and solar systems increase home value and appeal, especially in environmentally conscious mountain communities.' },
      { title: 'Colorado Sunshine', description: 'With 300+ days of sunshine, Colorado is one of the best states for both skylights and solar energy production.' },
    ],
    faqs: [
      { question: 'Will a skylight leak?', answer: 'Not when properly installed. Our comprehensive flashing system with ice and water shield protection ensures a watertight seal. We warranty our skylight installations against leaks.' },
      { question: 'Can skylights handle heavy snow loads?', answer: 'Yes, premium skylights like VELUX are rated for significant snow loads. The sloped glass also helps snow slide off naturally. We select products rated for your specific elevation and snow zone.' },
      { question: 'Do you install solar panels?', answer: 'We partner with certified solar installers and handle the roofing integration — ensuring all roof penetrations are properly flashed and sealed. This protects your roof warranty while enabling solar energy.' },
      { question: 'Can I add a skylight to an existing roof?', answer: 'In most cases, yes. We evaluate your roof structure and attic space to determine feasibility. Some installations require minor structural modifications that we can handle.' },
    ],
    metaDescription: 'Skylight installation and solar integration for Colorado mountain homes. Premium VELUX skylights, solar-ready roofing, and expert waterproofing. Alpine Peak Roofing.',
    relatedServices: ['complete-roof-replacement', 'new-construction', 'ventilation'],
  },
];

export const commercialServices: ServiceDetail[] = [
  {
    slug: 'flat-roof-systems',
    category: 'commercial',
    title: 'Flat Roof Systems',
    shortTitle: 'Flat Roof Systems',
    tagline: 'TPO, EPDM, and built-up roofing systems for commercial buildings in mountain environments.',
    description: 'Commercial flat roofs in Colorado\'s mountains face unique challenges that demand specialized expertise. From heavy snow accumulation and freeze-thaw cycling to intense UV exposure at altitude, your flat roof system must be engineered for extreme conditions. Alpine Peak Roofing installs and maintains all major flat roofing systems including TPO (Thermoplastic Polyolefin), EPDM (Ethylene Propylene Diene Monomer), PVC, and modified bitumen. We design each system with proper drainage slopes, reinforced membranes at high-stress areas, and insulation values optimized for mountain energy codes. Our commercial team has completed flat roof projects on mountain resort buildings, retail centers, restaurants, and municipal facilities throughout Colorado\'s high country.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-flat-roof-jsPX2c97WuFtZC56eyAc6P.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-flat-roof-B5faZkXTKv9HUbhbea2mWW.png',
    icon: 'Building2',
    features: [
      'TPO single-ply membrane systems',
      'EPDM rubber roofing installation',
      'PVC membrane for chemical resistance',
      'Modified bitumen multi-layer systems',
      'Tapered insulation for proper drainage',
      'Reinforced membrane at penetrations and edges',
      'Commercial-grade flashing and counterflashing',
      'Manufacturer NDL (No Dollar Limit) warranties available',
    ],
    process: [
      { step: 'Building Assessment', description: 'Comprehensive evaluation of your existing roof system, structural capacity, drainage patterns, and insulation. Core samples taken to assess existing layers.' },
      { step: 'System Specification', description: 'We specify the optimal flat roof system based on your building\'s use, budget, energy requirements, and expected lifespan. Full engineering drawings provided.' },
      { step: 'Tear-Off or Overlay', description: 'Depending on existing conditions, we either remove old roofing to the deck or install over existing layers when structurally appropriate.' },
      { step: 'Insulation & Drainage', description: 'Tapered insulation boards are installed to create positive drainage slopes. R-value meets or exceeds current energy code requirements.' },
      { step: 'Membrane Installation', description: 'Roofing membrane is installed by manufacturer-certified crews using heat-welded seams (TPO/PVC) or adhesive application (EPDM) for watertight performance.' },
      { step: 'Warranty & Documentation', description: 'Final inspection, warranty registration, and comprehensive maintenance documentation. NDL warranties available on qualifying installations.' },
    ],
    benefits: [
      { title: 'Long-Term Performance', description: 'Modern flat roof systems deliver 20-30+ year service life when properly installed and maintained in mountain conditions.' },
      { title: 'Energy Efficiency', description: 'Reflective TPO and PVC membranes reduce cooling costs, while upgraded insulation minimizes heating expenses in Colorado winters.' },
      { title: 'Low Maintenance', description: 'Single-ply membrane systems require minimal maintenance compared to older built-up roofing, reducing long-term operating costs.' },
      { title: 'Manufacturer Warranties', description: 'As certified installers, we can offer manufacturer NDL warranties that cover both materials and labor for the full warranty period.' },
    ],
    faqs: [
      { question: 'Which flat roof system is best for Colorado mountains?', answer: 'TPO is our most popular recommendation for its balance of performance, cost, and reflectivity. EPDM is excellent for budget-conscious projects. PVC is ideal for restaurants and buildings with rooftop grease exposure. We\'ll recommend the best option for your specific situation.' },
      { question: 'How do flat roofs handle heavy snow?', answer: 'We engineer flat roof systems with proper structural support for Colorado snow loads (typically 30-80 psf depending on location). Tapered insulation creates drainage slopes that help manage snowmelt.' },
      { question: 'How long does a commercial flat roof last?', answer: 'TPO and PVC systems typically last 20-30 years. EPDM can last 25-30+ years. Modified bitumen systems last 15-20 years. Proper maintenance extends all these lifespans significantly.' },
      { question: 'Can you work on occupied buildings?', answer: 'Yes, we regularly complete flat roof projects on occupied commercial buildings. We coordinate work to minimize disruption to your business operations and tenants.' },
    ],
    metaDescription: 'Commercial flat roof systems for Colorado mountain buildings. TPO, EPDM, PVC, and modified bitumen installation. Alpine Peak Roofing — certified commercial roofers.',
    relatedServices: ['commercial-metal-roofing', 'commercial-maintenance', 'roof-coatings'],
  },
  {
    slug: 'commercial-metal-roofing',
    category: 'commercial',
    title: 'Commercial Metal Roofing',
    shortTitle: 'Metal Roofing',
    tagline: 'Standing seam and metal panel systems for commercial and resort properties.',
    description: 'Metal roofing is the premium choice for commercial buildings in Colorado\'s mountain communities, offering unmatched durability, snow-shedding performance, and architectural appeal. Alpine Peak Roofing installs commercial-grade standing seam metal roofing systems on resort lodges, retail buildings, restaurants, municipal facilities, and multi-family properties throughout the high country. Our commercial metal installations feature concealed fastener standing seam panels that expand and contract with temperature changes without compromising weathertightness. We work with premium manufacturers to offer a full range of panel profiles, gauges, and factory-applied finishes including Kynar 500 coatings that maintain their appearance for decades. For mountain resort and hospitality properties, we specialize in complex architectural metal work including curved panels, custom trim, and mixed-material designs.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-metal-NCiYkH94aHRvCT8H2bkn7y.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-metal-YukPGFEQXciUMry8arMrSG.png',
    icon: 'Factory',
    features: [
      'Standing seam concealed fastener systems',
      'Architectural metal panel installation',
      'Kynar 500/Hylar 5000 factory finishes',
      'Custom panel fabrication and forming',
      'Curved and tapered panel installations',
      'Snow guard and retention systems',
      'Integrated gutter and drainage systems',
      'Multi-story and high-access capabilities',
    ],
    process: [
      { step: 'Project Consultation', description: 'We meet with building owners, architects, and property managers to understand project requirements, aesthetics, budget, and timeline.' },
      { step: 'Engineering & Design', description: 'Structural analysis, panel layout design, and material specification. We provide shop drawings and color samples for approval.' },
      { step: 'Material Procurement', description: 'Panels are ordered from premium manufacturers with specified gauge, profile, and finish. Custom lengths minimize on-site seams.' },
      { step: 'Substrate Preparation', description: 'Existing roofing is removed or overlaid as appropriate. Substrate is prepared with proper underlayment and clip systems.' },
      { step: 'Panel Installation', description: 'Standing seam panels are installed by our experienced metal roofing crews. Each panel is mechanically seamed for maximum weather resistance.' },
      { step: 'Trim & Completion', description: 'Custom trim, ridge caps, snow guards, and drainage components are installed. Final inspection ensures every detail meets our quality standards.' },
    ],
    benefits: [
      { title: '50+ Year Lifespan', description: 'Commercial metal roofing systems routinely last 50-70 years with minimal maintenance, making them the most cost-effective long-term roofing solution.' },
      { title: 'Snow Performance', description: 'Metal\'s smooth surface sheds snow efficiently, reducing structural loads. Snow guard systems control snow release to protect pedestrians and landscaping below.' },
      { title: 'Fire Resistance', description: 'Metal roofing carries a Class A fire rating — the highest available — providing critical protection for commercial properties in wildfire-prone mountain areas.' },
      { title: 'Architectural Appeal', description: 'Standing seam metal enhances the mountain aesthetic of commercial buildings, complementing timber, stone, and glass architectural elements.' },
    ],
    faqs: [
      { question: 'Is metal roofing noisy during rain or hail?', answer: 'No. Commercial metal roofing is installed over solid substrate with insulation that dampens sound. Most building occupants cannot distinguish rain noise from other roof types.' },
      { question: 'What colors and finishes are available?', answer: 'We offer 40+ standard colors in Kynar 500 finish that resists fading for 30+ years. Custom colors are available for larger projects. Popular mountain choices include weathered copper, dark bronze, and slate gray.' },
      { question: 'How does metal handle expansion and contraction?', answer: 'Standing seam systems use floating clip attachments that allow panels to expand and contract freely with temperature changes — critical in Colorado where temperatures can swing 50°F in a single day.' },
      { question: 'Can metal roofing be installed over existing roofing?', answer: 'In many cases, yes. We evaluate the existing roof and structure to determine if an overlay is appropriate, which can save time and disposal costs.' },
    ],
    metaDescription: 'Commercial metal roofing for Colorado mountain buildings. Standing seam, architectural panels, resort properties. Alpine Peak Roofing — premium commercial metal specialists.',
    relatedServices: ['flat-roof-systems', 'commercial-maintenance', 'snow-ice-management'],
  },
  {
    slug: 'commercial-maintenance',
    category: 'commercial',
    title: 'Preventive Maintenance Programs',
    shortTitle: 'Maintenance Programs',
    tagline: 'Scheduled inspection and maintenance programs to maximize your commercial roof investment.',
    description: 'Your commercial roof is one of your building\'s most valuable assets, and proactive maintenance is the key to maximizing its lifespan and avoiding costly emergency repairs. Alpine Peak Roofing offers comprehensive preventive maintenance programs designed specifically for commercial buildings in Colorado\'s demanding mountain climate. Our programs include scheduled inspections, proactive repairs, detailed condition reporting, and budget forecasting for future capital expenditures. We maintain all commercial roof types including TPO, EPDM, PVC, modified bitumen, metal, and built-up systems. Each inspection follows a standardized 50+ point checklist that evaluates membrane condition, seam integrity, flashing, drainage, penetrations, and structural components. We document everything with photos and provide actionable reports that help you plan maintenance budgets and extend your roof\'s service life.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-maintenance-UNSzeHP6i2Dn34ipUABau8.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-maintenance-LTBc599S3JZMHycgqqmPTU.png',
    icon: 'ClipboardCheck',
    features: [
      'Semi-annual or quarterly inspection programs',
      '50+ point standardized inspection checklist',
      'Photo-documented condition reports',
      'Proactive repair of minor issues before they escalate',
      'Drain clearing and debris removal',
      'Sealant and caulking maintenance',
      'Capital expenditure budget forecasting',
      'Emergency priority response for program members',
    ],
    process: [
      { step: 'Initial Assessment', description: 'Comprehensive baseline inspection of your entire roof system. We document current condition, identify existing issues, and establish maintenance priorities.' },
      { step: 'Program Design', description: 'We create a customized maintenance schedule based on your roof type, age, condition, and budget. Semi-annual inspections are standard; quarterly available for older systems.' },
      { step: 'Scheduled Inspections', description: 'Our certified inspectors perform thorough evaluations following our standardized checklist. All findings are documented with photos and condition ratings.' },
      { step: 'Proactive Repairs', description: 'Minor issues identified during inspections are repaired immediately — loose flashing, deteriorated sealant, small membrane damage, and clogged drains.' },
      { step: 'Reporting & Planning', description: 'You receive detailed reports after each inspection with condition ratings, completed repairs, and recommendations for future maintenance or capital improvements.' },
    ],
    benefits: [
      { title: 'Extended Roof Life', description: 'Regular maintenance can extend your commercial roof\'s lifespan by 25-50%, delaying expensive replacement by years or even decades.' },
      { title: 'Cost Savings', description: 'Proactive maintenance costs a fraction of emergency repairs. Catching problems early prevents water damage to building interiors and inventory.' },
      { title: 'Warranty Compliance', description: 'Most manufacturer warranties require regular maintenance. Our documented inspections keep your warranty valid and claims-ready.' },
      { title: 'Budget Predictability', description: 'Our condition reports and forecasting help you plan maintenance budgets and capital expenditures years in advance.' },
    ],
    faqs: [
      { question: 'How often should a commercial roof be inspected?', answer: 'We recommend semi-annual inspections — once in spring (after winter) and once in fall (before winter). Older roofs or those with known issues benefit from quarterly inspections.' },
      { question: 'What does a maintenance program cost?', answer: 'Programs are customized based on roof size, type, and condition. Most programs cost 1-3% of the roof\'s replacement value annually — a fraction of what emergency repairs or premature replacement would cost.' },
      { question: 'Do you maintain roofs installed by other companies?', answer: 'Yes, we maintain all commercial roof types regardless of who installed them. Our initial assessment establishes a baseline condition report for ongoing maintenance.' },
      { question: 'What happens if you find a major issue during inspection?', answer: 'We document the issue with photos and provide a detailed repair proposal with options and pricing. For urgent issues, we can often provide temporary protection immediately while permanent repairs are scheduled.' },
    ],
    metaDescription: 'Commercial roof maintenance programs in Colorado mountains. Scheduled inspections, proactive repairs, and budget forecasting. Alpine Peak Roofing protects your investment.',
    relatedServices: ['flat-roof-systems', 'commercial-metal-roofing', 'roof-coatings'],
  },
  {
    slug: 'roof-coatings',
    category: 'commercial',
    title: 'Roof Coating Systems',
    shortTitle: 'Roof Coatings',
    tagline: 'Reflective and protective coating systems that extend roof life and improve energy efficiency.',
    description: 'Roof coating systems offer a cost-effective way to extend the life of your existing commercial roof while improving energy efficiency and reducing environmental impact. Alpine Peak Roofing applies premium elastomeric, silicone, and acrylic roof coatings that create a seamless, waterproof membrane over your existing roof surface. These coatings are particularly effective in Colorado\'s mountain climate, where intense UV radiation at altitude accelerates roof aging. A reflective white coating can reduce roof surface temperature by up to 80°F on sunny days, significantly lowering cooling costs and reducing thermal stress on the membrane below. Coating systems can add 10-15 years of service life to an aging roof at a fraction of replacement cost, making them an excellent option for building owners looking to maximize their roofing investment.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-coating-Jt3JtmEoxWQUyDmA6R6QKZ.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-coating-9wnmk38BcE9TapvFv29gy7.png',
    icon: 'Paintbrush',
    features: [
      'Silicone roof coating systems',
      'Acrylic elastomeric coatings',
      'Polyurethane foam and coating systems',
      'Reflective cool roof technology',
      'Seamless waterproof membrane creation',
      'UV protection for aging membranes',
      'Ponding water-rated silicone options',
      'ENERGY STAR qualified systems',
    ],
    process: [
      { step: 'Roof Evaluation', description: 'We assess your existing roof\'s condition, type, and remaining life to determine if coating is appropriate. Core samples may be taken to evaluate moisture levels.' },
      { step: 'Coating Selection', description: 'Based on your roof type and conditions, we recommend the optimal coating system. Silicone for ponding water areas, acrylic for sloped surfaces, or polyurethane for added insulation.' },
      { step: 'Surface Preparation', description: 'The existing roof is thoroughly cleaned, repaired, and primed. All seams, penetrations, and detail areas receive reinforcing fabric and additional coating.' },
      { step: 'Coating Application', description: 'Multiple coats are applied using spray or roller equipment to achieve specified mil thickness. Each coat is inspected before the next is applied.' },
      { step: 'Quality Assurance', description: 'Final thickness measurements, adhesion testing, and visual inspection ensure the coating meets manufacturer specifications. Warranty documentation provided.' },
    ],
    benefits: [
      { title: 'Cost Savings', description: 'Coating systems typically cost 50-70% less than full roof replacement while adding 10-15 years of service life to your existing roof.' },
      { title: 'Energy Efficiency', description: 'Reflective coatings reduce roof surface temperature by up to 80°F, lowering cooling costs by 10-30% and qualifying for energy rebates.' },
      { title: 'Sustainability', description: 'Coating avoids sending old roofing materials to landfills and reduces the carbon footprint associated with manufacturing new roofing products.' },
      { title: 'Minimal Disruption', description: 'Coating application is faster and less disruptive than replacement. No tear-off noise, no debris, and your building stays fully operational.' },
    ],
    faqs: [
      { question: 'Is my roof a good candidate for coating?', answer: 'Most commercial roofs in fair to good condition are candidates. The existing membrane must be structurally sound and free of excessive moisture. We perform a thorough evaluation to determine suitability.' },
      { question: 'How long do roof coatings last?', answer: 'Quality silicone coatings last 10-15 years and can be recoated indefinitely. Acrylic coatings typically last 8-12 years. The key is proper surface preparation and adequate coating thickness.' },
      { question: 'Can coatings be applied in cold weather?', answer: 'Acrylic coatings require temperatures above 50°F. Silicone coatings can be applied in cooler temperatures. We schedule applications during appropriate weather windows for your elevation.' },
      { question: 'Do coatings qualify for tax incentives?', answer: 'Yes, ENERGY STAR qualified reflective coatings may qualify for federal tax deductions under Section 179D and various utility rebate programs. We can provide documentation for your tax advisor.' },
    ],
    metaDescription: 'Commercial roof coating systems in Colorado. Silicone, acrylic, and elastomeric coatings extend roof life and improve energy efficiency. Alpine Peak Roofing.',
    relatedServices: ['flat-roof-systems', 'commercial-maintenance', 'commercial-emergency'],
  },
  {
    slug: 'snow-ice-management',
    category: 'commercial',
    title: 'Snow & Ice Management',
    shortTitle: 'Snow & Ice',
    tagline: 'Professional snow removal, ice dam prevention, and winter roof protection for commercial properties.',
    description: 'Colorado mountain communities receive 150-400+ inches of snowfall annually, creating significant challenges for commercial building roofs. Excessive snow accumulation can exceed structural load limits, while ice dams cause water infiltration and interior damage. Alpine Peak Roofing provides comprehensive snow and ice management services for commercial properties, including emergency snow removal, ice dam prevention systems, and heated cable installations. Our team monitors weather conditions and snow accumulation levels, proactively responding when your building approaches critical load thresholds. We use specialized equipment designed for commercial rooftops, including low-impact snow removal tools that protect your roof membrane while efficiently clearing dangerous accumulations. For long-term solutions, we design and install heated cable systems along eaves, valleys, and gutters that prevent ice dam formation automatically.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-snow-YRrN3T2unRtuGMJbvsnVn6.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-snow-QpwsRRqcBX2YNkBtxpevbx.png',
    icon: 'Snowflake',
    features: [
      'Emergency commercial snow removal',
      'Snow load monitoring and alerts',
      'Ice dam prevention and removal',
      'Heated cable system installation',
      'Roof-safe snow removal equipment',
      'Structural load assessment',
      'Seasonal snow management contracts',
      'Priority response for contract customers',
    ],
    process: [
      { step: 'Risk Assessment', description: 'We evaluate your building\'s structural snow load capacity, identify vulnerable areas prone to drifting and ice dams, and establish trigger thresholds for snow removal.' },
      { step: 'Prevention Planning', description: 'For long-term solutions, we design heated cable systems and ventilation improvements that prevent ice dams and reduce snow accumulation in problem areas.' },
      { step: 'Monitoring', description: 'During winter months, we monitor weather forecasts and snow accumulation. Contract customers receive proactive notifications when removal may be needed.' },
      { step: 'Safe Removal', description: 'Our trained crews use roof-safe equipment to remove snow without damaging your roof membrane. We follow strict safety protocols for working at height in winter conditions.' },
      { step: 'Documentation', description: 'Each service visit is documented with photos and snow depth measurements. Reports are provided for insurance and building management records.' },
    ],
    benefits: [
      { title: 'Structural Protection', description: 'Prevent roof collapse from excessive snow loads. Colorado building codes require roofs to handle 30-80 psf, but drifting can create loads exceeding design limits.' },
      { title: 'Water Damage Prevention', description: 'Ice dams force water under roofing materials and into your building. Prevention and removal services protect your interior, inventory, and equipment.' },
      { title: 'Liability Reduction', description: 'Controlled snow removal prevents dangerous avalanching from commercial roofs that can injure pedestrians and damage vehicles below.' },
      { title: 'Business Continuity', description: 'Proactive snow management prevents emergency closures due to roof leaks or structural concerns during peak winter business season.' },
    ],
    faqs: [
      { question: 'How much snow is too much for my commercial roof?', answer: 'It depends on your building\'s structural design. Fresh snow weighs about 5-20 psf per foot of depth, while packed snow can weigh 20-40 psf. We calculate your building\'s specific threshold and monitor accordingly.' },
      { question: 'How quickly can you respond to a snow emergency?', answer: 'Contract customers receive priority response, typically within 4-8 hours. Non-contract emergency calls are handled as quickly as possible based on crew availability and conditions.' },
      { question: 'Won\'t snow removal damage my roof?', answer: 'Not when done properly. We use plastic shovels, roof rakes, and other membrane-safe tools. We leave a thin layer of snow on the roof rather than scraping to the membrane surface.' },
      { question: 'What are heated cable systems?', answer: 'Self-regulating heated cables installed along eaves, in valleys, and through gutters that automatically activate in freezing conditions to prevent ice dam formation. They\'re energy-efficient and require minimal maintenance.' },
    ],
    metaDescription: 'Commercial snow removal and ice dam prevention in Colorado mountains. Emergency response, heated cable systems, and seasonal contracts. Alpine Peak Roofing.',
    relatedServices: ['commercial-metal-roofing', 'commercial-maintenance', 'commercial-emergency'],
  },
  {
    slug: 'commercial-emergency',
    category: 'commercial',
    title: 'Emergency Commercial Repairs',
    shortTitle: 'Emergency Repairs',
    tagline: '24/7 emergency response for commercial roof damage, leaks, and storm events.',
    description: 'When your commercial roof is compromised, every minute counts. Water infiltration can damage inventory, equipment, and building systems, disrupt business operations, and create safety hazards for occupants. Alpine Peak Roofing provides 24/7 emergency response for commercial buildings throughout Colorado\'s mountain communities. Our emergency crews are equipped with tarps, temporary repair materials, and the expertise to stabilize your roof quickly and effectively. We respond to all types of commercial roof emergencies including storm damage, wind uplift, falling tree impacts, equipment damage, and sudden leak events. Once temporary protection is in place, we provide a comprehensive damage assessment and permanent repair plan, and we work directly with your insurance company to streamline the claims process.',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-emergency-C7f8SeMSrMo3AUEsvJHGoh.webp',
    heroImage: 'https://d2xsxph8kpxj0f.cloudfront.net/112751785/9NG5n2RUouX55uKeRwTfKV/service-commercial-emergency-MpUVvR9b2ehqHmDY9Sxxg6.png',
    icon: 'AlertTriangle',
    features: [
      '24/7 emergency hotline and dispatch',
      'Rapid temporary protection and tarping',
      'Storm damage assessment and documentation',
      'Insurance claim assistance and coordination',
      'Permanent repair planning and execution',
      'Water extraction coordination',
      'Board-up and security services',
      'Multi-building portfolio emergency management',
    ],
    process: [
      { step: 'Emergency Call', description: 'Call our 24/7 emergency line at (970) 446-8995. Our dispatcher gathers critical information and mobilizes the nearest available crew.' },
      { step: 'Rapid Response', description: 'Our emergency crew arrives with tarps, temporary repair materials, and safety equipment. Priority is stopping water infiltration and securing the building.' },
      { step: 'Temporary Protection', description: 'We install emergency tarps, apply temporary patches, and take whatever measures are needed to protect your building until permanent repairs can be made.' },
      { step: 'Damage Assessment', description: 'Once the emergency is stabilized, we perform a comprehensive assessment documenting all damage with photos, measurements, and moisture readings.' },
      { step: 'Insurance Coordination', description: 'We provide detailed documentation for your insurance claim and work directly with adjusters to ensure fair coverage of repair costs.' },
      { step: 'Permanent Repair', description: 'We develop and execute a permanent repair plan that addresses all damage and prevents recurrence. Quality materials and workmanship backed by our warranty.' },
    ],
    benefits: [
      { title: 'Minimize Damage', description: 'Rapid response limits water infiltration and prevents secondary damage to building interiors, equipment, and inventory.' },
      { title: 'Business Continuity', description: 'Quick temporary repairs allow your business to continue operating while permanent solutions are planned and executed.' },
      { title: 'Insurance Support', description: 'Our detailed documentation and direct coordination with insurance adjusters streamlines the claims process and maximizes coverage.' },
      { title: 'Single Point of Contact', description: 'From emergency response through permanent repair, you work with one team that knows your building and your situation.' },
    ],
    faqs: [
      { question: 'How quickly can you respond to an emergency?', answer: 'We maintain emergency crews throughout our service area. Response times vary by location and conditions, but we typically arrive within 2-6 hours for true emergencies.' },
      { question: 'Do you work with insurance companies?', answer: 'Yes, we work with all major insurance carriers. We provide the documentation they need, meet with adjusters on-site, and can supplement claims when initial assessments undervalue damage.' },
      { question: 'What should I do while waiting for your crew?', answer: 'If safe to do so, move valuable items away from the leak area, place containers to catch water, and document the damage with photos. Do not go on the roof yourself.' },
      { question: 'Is emergency service more expensive?', answer: 'Emergency temporary protection is billed at standard rates plus any after-hours premium. Permanent repairs are priced the same as non-emergency work. We\'re transparent about all costs upfront.' },
    ],
    metaDescription: '24/7 emergency commercial roof repair in Colorado mountains. Rapid response, storm damage, insurance coordination. Alpine Peak Roofing emergency services.',
    relatedServices: ['flat-roof-systems', 'commercial-maintenance', 'snow-ice-management'],
  },
];

export const allServices = [...residentialServices, ...commercialServices];

export function getServiceBySlug(slug: string): ServiceDetail | undefined {
  return allServices.find(s => s.slug === slug);
}

export function getRelatedServices(slugs: string[]): ServiceDetail[] {
  return slugs.map(slug => allServices.find(s => s.slug === slug)).filter(Boolean) as ServiceDetail[];
}
